services:
  - type: web
    name: my-portfolio
    env: static
    buildCommand: npm install && npm run build  # Simplified now that conflict is resolved
    staticPublishPath: ./dist  # or `./build` for Create React App